/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Jgd0ueWzFxp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/* Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Judson } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})
*/

import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function StartCall() {
  return (
    <div className="w-full max-w-2xl mx-auto p-6 md:p-8 border border-gray-200 rounded-lg shadow-md dark:border-gray-800">
      <h1 className="text-2xl font-bold mb-6">Customer Information</h1>
      <div className="grid grid-cols-2 gap-4 mb-6">
        <div className="space-y-2">
          <Label htmlFor="customer">Customer</Label>
          <Select className="w-full" id="customer">
            <SelectTrigger>
              <SelectValue placeholder="Select customer" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="customer1">Customer 1</SelectItem>
              <SelectItem value="customer2">Customer 2</SelectItem>
              <SelectItem value="customer3">Customer 3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="problem">Problem</Label>
          <Select className="w-full" id="problem">
            <SelectTrigger>
              <SelectValue placeholder="Select problem" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="problem1">Problem 1</SelectItem>
              <SelectItem value="problem2">Problem 2</SelectItem>
              <SelectItem value="problem3">Problem 3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="phone">Phone Number</Label>
          <Input id="phone" placeholder="Enter phone number" type="tel" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="name">Name</Label>
          <Input id="name" placeholder="Enter name" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="anydesk">Clients Anydesk</Label>
          <Input id="anydesk" placeholder="Enter Anydesk ID" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="type">Type</Label>
          <Select className="w-full" id="type">
            <SelectTrigger>
              <SelectValue placeholder="Select type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="type1">Type 1</SelectItem>
              <SelectItem value="type2">Type 2</SelectItem>
              <SelectItem value="type3">Type 3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="employee">Employee</Label>
          <Select className="w-full" id="employee">
            <SelectTrigger>
              <SelectValue placeholder="Select employee" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="employee1">Employee 1</SelectItem>
              <SelectItem value="employee2">Employee 2</SelectItem>
              <SelectItem value="employee3">Employee 3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="urgent">Urgent</Label>
          <Select className="w-full" id="urgent">
            <SelectTrigger>
              <SelectValue placeholder="Select urgency" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="low">Low</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="high">High</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="space-y-2">
        <Label htmlFor="comments">Comments</Label>
        <Textarea className="h-24" id="comments" placeholder="Enter comments" />
      </div>
      <div className="flex justify-between gap-2 mt-6">
        <Button className="flex-1" variant="outline">
          Take Call
        </Button>
        <Button className="flex-1" variant="outline">
          Cancel
        </Button>
        <Button className="flex-1">Save</Button>
      </div>
    </div>
  )
}
