/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RQpIYIhiPb8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { JSX, SVGProps } from "react"

export function TicketsTable() {
  return (
    <div className="h-screen w-full overflow-auto">
      <header className="bg-gray-900 text-gray-50 px-4 py-2 flex items-center justify-between rounded-r-lg">
        <nav className="flex items-center space-x-4">
          <Button variant="ghost">
            <span>Search</span>
          </Button>
          <Button variant="ghost">
            <span>Start Call</span>
          </Button>
          <Button variant="ghost">
            <span>End Call</span>
          </Button>
          <Button variant="ghost">
            <span>Start Activity</span>
          </Button>
          <Button variant="ghost">
            <span>End Activity</span>
          </Button>
          <Button variant="ghost">
            <span>Start Break</span>
          </Button>
          <Button variant="ghost">
            <span>End Break</span>
          </Button>
        </nav>
        <div className="flex items-center space-x-4">
          <Button size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">User Menu</span>
          </Button>
        </div>
      </header>
      <div className="grid gap-6">
        <div className="max-h-[600px] overflow-auto">
          <Card>
            <CardHeader className="p-6 flex items-center">
              <CardTitle className="text-lg">Tickets being worked on</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="max-h-[400px] overflow-auto">
                <Table className="w-full">
                  <TableHeader>
                    <TableRow className="text-sm font-medium">
                      <TableHead className="w-[100px] text-left">Call ID</TableHead>
                      <TableHead className="text-left">Customer</TableHead>
                      <TableHead className="text-left">Problem</TableHead>
                      <TableHead className="text-left">Client Name</TableHead>
                      <TableHead className="text-center">Time</TableHead>
                      <TableHead className="w-[100px] text-left">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">34567</TableCell>
                      <TableCell>John Doe</TableCell>
                      <TableCell>Internet Issue</TableCell>
                      <TableCell>Acme Inc</TableCell>
                      <TableCell className="text-center">10m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34568</TableCell>
                      <TableCell>Jane Smith</TableCell>
                      <TableCell>Wifi Problem</TableCell>
                      <TableCell>BizTech</TableCell>
                      <TableCell className="text-center">5m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34569</TableCell>
                      <TableCell>Robert Johnson</TableCell>
                      <TableCell>Slow Connection</TableCell>
                      <TableCell>MicroData</TableCell>
                      <TableCell className="text-center">15m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34570</TableCell>
                      <TableCell>Lisa Brown</TableCell>
                      <TableCell>Connection Drop</TableCell>
                      <TableCell>ConnectX</TableCell>
                      <TableCell className="text-center">8m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34571</TableCell>
                      <TableCell>Mike Lee</TableCell>
                      <TableCell>No Access</TableCell>
                      <TableCell>TechNet</TableCell>
                      <TableCell className="text-center">12m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="max-h-[600px] overflow-auto">
          <Card>
            <CardHeader className="p-6 flex items-center">
              <CardTitle className="text-lg">Tickets being worked on</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="max-h-[400px] overflow-auto">
                <Table className="w-full">
                  <TableHeader>
                    <TableRow className="text-sm font-medium">
                      <TableHead className="w-[100px] text-left">Call ID</TableHead>
                      <TableHead className="text-left">Customer</TableHead>
                      <TableHead className="text-left">Problem</TableHead>
                      <TableHead className="text-left">Client Name</TableHead>
                      <TableHead className="text-center">Time</TableHead>
                      <TableHead className="w-[100px] text-left">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">34567</TableCell>
                      <TableCell>John Doe</TableCell>
                      <TableCell>Internet Issue</TableCell>
                      <TableCell>Acme Inc</TableCell>
                      <TableCell className="text-center">10m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34568</TableCell>
                      <TableCell>Jane Smith</TableCell>
                      <TableCell>Wifi Problem</TableCell>
                      <TableCell>BizTech</TableCell>
                      <TableCell className="text-center">5m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34569</TableCell>
                      <TableCell>Robert Johnson</TableCell>
                      <TableCell>Slow Connection</TableCell>
                      <TableCell>MicroData</TableCell>
                      <TableCell className="text-center">15m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34570</TableCell>
                      <TableCell>Lisa Brown</TableCell>
                      <TableCell>Connection Drop</TableCell>
                      <TableCell>ConnectX</TableCell>
                      <TableCell className="text-center">8m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34571</TableCell>
                      <TableCell>Mike Lee</TableCell>
                      <TableCell>No Access</TableCell>
                      <TableCell>TechNet</TableCell>
                      <TableCell className="text-center">12m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

export function EyeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


export function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
