/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RQpIYIhiPb8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { JSX, SVGProps } from "react"

export function TicketsTable() {
  return (
    <div className="h-screen w-full overflow-auto">
      <header className="bg-gray-900 text-gray-50 px-4 py-2 flex items-center justify-between rounded-r-lg">
        <nav className="flex items-center space-x-4">
          <Button variant="ghost">
            <span>Search</span>
          </Button>
          <Button variant="ghost">
            <span>Start Call</span>
          </Button>
          <Button variant="ghost">
            <span>End Call</span>
          </Button>
          <Button variant="ghost">
            <span>Start Activity</span>
          </Button>
          <Button variant="ghost">
            <span>End Activity</span>
          </Button>
          <Button variant="ghost">
            <span>Start Break</span>
          </Button>
          <Button variant="ghost">
            <span>End Break</span>
          </Button>
        </nav>
        <div className="flex items-center space-x-4">
          <Button size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">User Menu</span>
          </Button>
        </div>
      </header>
      <div className="grid gap-6">
        <div className="max-h-[600px] overflow-auto">
          <Card>
            <CardHeader className="p-6 flex items-center">
              <CardTitle className="text-lg">Tickets being worked on</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="max-h-[400px] overflow-auto">
                <Table className="w-full">
                  <TableHeader>
                    <TableRow className="text-sm font-medium">
                      <TableHead className="w-[100px] text-left">Call ID</TableHead>
                      <TableHead className="text-left">Customer</TableHead>
                      <TableHead className="text-left">Problem</TableHead>
                      <TableHead className="text-left">Client Name</TableHead>
                      <TableHead className="text-center">Time</TableHead>
                      <TableHead className="w-[100px] text-left">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">34567</TableCell>
                      <TableCell>John Doe</TableCell>
                      <TableCell>Internet Issue</TableCell>
                      <TableCell>Acme Inc</TableCell>
                      <TableCell className="text-center">10m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34568</TableCell>
                      <TableCell>Jane Smith</TableCell>
                      <TableCell>Wifi Problem</TableCell>
                      <TableCell>BizTech</TableCell>
                      <TableCell className="text-center">5m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34569</TableCell>
                      <TableCell>Robert Johnson</TableCell>
                      <TableCell>Slow Connection</TableCell>
                      <TableCell>MicroData</TableCell>
                      <TableCell className="text-center">15m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34570</TableCell>
                      <TableCell>Lisa Brown</TableCell>
                      <TableCell>Connection Drop</TableCell>
                      <TableCell>ConnectX</TableCell>
                      <TableCell className="text-center">8m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34571</TableCell>
                      <TableCell>Mike Lee</TableCell>
                      <TableCell>No Access</TableCell>
                      <TableCell>TechNet</TableCell>
                      <TableCell className="text-center">12m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="max-h-[600px] overflow-auto">
          <Card>
            <CardHeader className="p-6 flex items-center">
              <CardTitle className="text-lg">Tickets being worked on</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="max-h-[400px] overflow-auto">
                <Table className="w-full">
                  <TableHeader>
                    <TableRow className="text-sm font-medium">
                      <TableHead className="w-[100px] text-left">Call ID</TableHead>
                      <TableHead className="text-left">Customer</TableHead>
                      <TableHead className="text-left">Problem</TableHead>
                      <TableHead className="text-left">Client Name</TableHead>
                      <TableHead className="text-center">Time</TableHead>
                      <TableHead className="w-[100px] text-left">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">34567</TableCell>
                      <TableCell>John Doe</TableCell>
                      <TableCell>Internet Issue</TableCell>
                      <TableCell>Acme Inc</TableCell>
                      <TableCell className="text-center">10m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34568</TableCell>
                      <TableCell>Jane Smith</TableCell>
                      <TableCell>Wifi Problem</TableCell>
                      <TableCell>BizTech</TableCell>
                      <TableCell className="text-center">5m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34569</TableCell>
                      <TableCell>Robert Johnson</TableCell>
                      <TableCell>Slow Connection</TableCell>
                      <TableCell>MicroData</TableCell>
                      <TableCell className="text-center">15m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34570</TableCell>
                      <TableCell>Lisa Brown</TableCell>
                      <TableCell>Connection Drop</TableCell>
                      <TableCell>ConnectX</TableCell>
                      <TableCell className="text-center">8m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">34571</TableCell>
                      <TableCell>Mike Lee</TableCell>
                      <TableCell>No Access</TableCell>
                      <TableCell>TechNet</TableCell>
                      <TableCell className="text-center">12m</TableCell>
                      <TableCell className="text-center">
                        <div className="flex gap-2">
                          <Button size="sm">
                            <span>View</span>
                            <EyeIcon className="h-4 w-4 ml-2" />
                          </Button>
                          <Button size="sm">
                            <span>Take</span>
                            <PlusIcon className="h-4 w-4 ml-2" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

export function EyeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}

export function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}

export function MinusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  )
}

export function ActivityIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


export function CoffeeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 2v2" />
      <path d="M14 2v2" />
      <path d="M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1" />
      <path d="M6 2v2" />
    </svg>
  )
}


export function MoveIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="5 9 2 12 5 15" />
      <polyline points="9 5 12 2 15 5" />
      <polyline points="15 19 12 22 9 19" />
      <polyline points="19 9 22 12 19 15" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>
  )
}


export function PhoneIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


export function PhoneOffIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10.68 13.31a16 16 0 0 0 3.41 2.6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7 2 2 0 0 1 1.72 2v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.42 19.42 0 0 1-3.33-2.67m-2.67-3.34a19.79 19.79 0 0 1-3.07-8.63A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91" />
      <line x1="22" x2="2" y1="2" y2="22" />
    </svg>
  )
}


export function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}